# Generated by Django 3.1.7 on 2021-02-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vanished',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=300)),
                ('missing_since', models.DateField(blank=True)),
                ('classification', models.CharField(choices=[('MISSING', 'Missing Person'), ('MYSTERIOUS', 'Mysterious Death'), ('UNSOLVED', 'Unsolved Homicide'), ('COURT', 'In Legal System'), ('CLOSED', 'Resolved in court system')], default='MISSING', max_length=40)),
                ('sex', models.CharField(max_length=2)),
                ('race', models.CharField(max_length=10)),
                ('dob', models.DateField(blank=True, verbose_name='Date of Birth')),
                ('age', models.IntegerField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('narrative', models.TextField(blank=True)),
                ('enrolled', models.BooleanField(blank=True)),
                ('tribe', models.TextField(blank=True)),
                ('lat', models.FloatField(blank=True, verbose_name='latitude')),
                ('lon', models.FloatField(blank=True, verbose_name='longitude')),
                ('loc_copy', models.TextField(blank=True)),
            ],
        ),
    ]
