# Generated by Django 3.1.7 on 2021-02-22 23:09

import cases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vanished',
            name='subject_name',
        ),
        migrations.AddField(
            model_name='vanished',
            name='first_name',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vanished',
            name='last_name',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vanished',
            name='middle_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vanished',
            name='photo',
            field=models.ImageField(blank=True, upload_to=cases.models.name_folder_path),
        ),
    ]
