# Generated by Django 3.1.7 on 2021-02-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20210222_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vanished',
            name='race',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='vanished',
            name='sex',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
