# Generated by Django 3.1.7 on 2021-02-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20210223_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vanished',
            name='age',
            field=models.IntegerField(blank=True, help_text='Age when went missing'),
        ),
        migrations.AlterField(
            model_name='vanished',
            name='dob',
            field=models.DateField(blank=True, help_text='Format: yyyy-mm-dd', verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='vanished',
            name='lat',
            field=models.FloatField(null=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='vanished',
            name='lon',
            field=models.FloatField(null=True, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='vanished',
            name='missing_since',
            field=models.DateField(blank=True, help_text='Format: yyyy-mm-dd'),
        ),
    ]
