# Generated by Django 3.1.7 on 2021-02-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_auto_20210223_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vanished',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='vanished',
            name='lon',
        ),
    ]
