# Generated by Django 3.1.7 on 2021-02-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_vanished_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanished',
            name='sources',
            field=models.TextField(blank=True),
        ),
    ]
