# Generated by Django 3.1.7 on 2021-02-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_vanished_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vanished',
            name='dob',
            field=models.DateField(blank=True, help_text='Format: yyyy-mm-dd', null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='vanished',
            name='missing_since',
            field=models.DateField(blank=True, help_text='Format: yyyy-mm-dd', null=True),
        ),
    ]
