# Generated by Django 3.1.7 on 2021-02-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_auto_20210223_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanished',
            name='missing_from',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
