# Generated by Django 3.1.7 on 2021-03-03 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_vanished_missing_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vanished',
            name='loc_copy',
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True)),
                ('hed', models.TextField(blank=True)),
                ('vanished', models.ManyToManyField(related_name='stories', to='cases.Vanished')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='latitude')),
                ('lon', models.FloatField(verbose_name='longitude')),
                ('loc_description', models.TextField(blank=True)),
                ('vanished', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.vanished')),
            ],
        ),
    ]
