# Generated by Django 3.1.7 on 2021-03-04 12:50

import cases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_auto_20210303_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='pub_date',
            field=models.DateField(null=True),
        ),
    ]
